[build]
  builder = "NIXPACKS"
  buildCommand = "npm ci --production"

[deploy]
  startCommand = "node src/server.js"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[healthcheck]
  path = "/health"
  timeout = 300